[project]
name = "domain-pack-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "deepdiff>=8.6.1",
    "fastmcp>=2.14.3",
    "mcp>=1.25.0",
    "psycopg2-binary>=2.9.11",
    "ruamel-yaml>=0.19.1",
]
